import React, { createContext, useContext, useEffect, useState, useMemo } from 'react';

export type LanguageCode = 
  | 'ar' // العربية
  | 'en' // English
  | 'fr' // Français
  | 'es' // Español
  | 'de' // Deutsch
  | 'tr' // Türkçe
  | 'ur' // اردو
  | 'hi' // हिन्दी
  | 'id' // Bahasa Indonesia
  | 'ms' // Bahasa Melayu
  | 'bn' // বাংলা
  | 'ru' // Русский
  | 'zh' // 中文
  | 'ja' // 日本語
  | 'ko' // 한국어
  | 'pt' // Português
  | 'it' // Italiano
  | 'fa'; // فارسی

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
  dir: 'rtl' | 'ltr';
  popular?: boolean;
}

export const LANGUAGES: LanguageInfo[] = [
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', dir: 'rtl', popular: true },
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸', dir: 'ltr', popular: true },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷', dir: 'ltr', popular: true },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷', dir: 'ltr', popular: true },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰', dir: 'rtl', popular: true },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', dir: 'ltr', popular: true },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩', dir: 'ltr' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', flag: '🇲🇾', dir: 'ltr' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩', dir: 'ltr' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'zh', name: 'Chinese', nativeName: '中文 (简体)', flag: '🇨🇳', dir: 'ltr' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', dir: 'ltr' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷', dir: 'ltr' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷', dir: 'ltr' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی', flag: '🇮🇷', dir: 'rtl' },
];

export const translations: Record<LanguageCode, Record<string, string>> = {
  ar: {
    // Brand & Main
    appName: 'مصاريف العائلة',
    appSubtitle: 'نظام إدارة الميزانية والمصاريف العائلية',
    founder: 'المؤسس',
    founderMode: 'لوحة المؤسس (رب الأسرة)',
    founderBadge: '👑 المؤسس',
    memberBadge: '👤 فرد من الأسرة',
    memberPersonalView: 'لوحة الحساب الشخصي',
    founderSubtitleFull: 'لوحة تحكم مؤسس العائلة (تحكم كامل بجميع الأفراد)',
    memberSubtitleFull: 'حساب شخصي: مصاريفي ودخلي فقط',
    welcome: 'مرحباً',
    totalBalance: 'صافي الميزانية',
    totalIncome: 'إجمالي الدخل',
    totalExpenses: 'إجمالي المصاريف',
    recurringMonthly: 'المصاريف المتكررة',
    addExpense: 'إضافة مصروف',
    addIncome: 'إضافة دخل',
    familyMembers: 'أفراد الأسرة',
    recurringExpenses: 'المصاريف المتكررة',
    exportReports: 'تصدير التقارير',
    changeLanguage: 'تغيير لغة التطبيق',
    changeCurrency: 'تغيير العملة',
    founderSecurityPin: 'الرمز السري للمؤسس',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب جديد',
    allMembers: 'جميع أفراد الأسرة',
    recentTransactions: 'سجل العمليات الأخير',
    searchPlaceholder: 'ابحث في الوصف، المستفيد، أو الوسوم...',
    noTransactionsFound: 'لا توجد معاملات مسجلة تطابق بحثك',
    filterBy: 'تصفية حسب',
    all: 'الكل',
    expense: 'مصروف',
    income: 'دخل',
    today: 'اليوم',
    yesterday: 'أمس',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    thisYear: 'هذا العام',
    customRange: 'مخصص',
    category: 'الفئة',
    amount: 'المبلغ',
    payer: 'الشخص الدافع',
    beneficiary: 'المستفيد',
    paymentMethod: 'طريقة الدفع',
    date: 'التاريخ',
    notes: 'ملاحظات',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    close: 'إغلاق',
    offline: 'دون اتصال (أوفلاين)',
    online: 'متصل سحابياً',
    demo: 'تجريبي',
    synced: 'تمت المزامنة السحابية',
    syncing: 'جاري المزامنة...',
    securityProtected: 'مؤمّن برمز سري ومحمي سحابياً',
    enterPin: 'أدخل الرمز السري',
    lockoutWarning: 'تم إيقاف الإدخال مؤقتاً بسبب تكرار الأخطاء',
    languageSelectorTitle: 'اختيار لغة التطبيق لجميع أفراد الأسرة',
    languageSelectorSubtitle: 'اختر لغتك المفضلة لتصفح الواجهة والتقارير بأريحية',
    currencySelectorTitle: 'اختيار عملة النظام لجميع دول العالم',
    activeLanguage: 'اللغة الحالية',
    founderPanelTitle: 'لوحة تحكم مؤسس العائلة (الإدارة الشاملة)',
    fullPrivileges: 'صلاحيات كاملة',
    founderPanelDesc: 'أنت الآن في وضع المؤسس: يمكنك مراقبة كل العمليات، تخصيص ميزانيات الأفراد، وإدارة الأسرة بالكامل.',
    viewingAllMembers: 'أنت تشاهد حالياً بيانات جميع أفراد الأسرة مجتمعة',
    personalBannerTitle: 'لوحة الحساب الشخصي',
    personalBannerDesc: 'أنت الآن في حسابك الشخصي المستقل. العمليات المسجلة هنا تخصك وتنعكس على ميزانيتك وميزانية الأسرة.',
    myTransactions: 'معاملاتي الشخصية',
    myExpenses: 'مصاريفي الشخصية',
    myIncome: 'دخلي الشخصي',
    myBalance: 'رصيدي الصافي',
    budgetLimit: 'سقف الميزانية المحدد',
    spentSoFar: 'تم صرفه حتى الآن',
    remaining: 'المتبقي',
    overBudget: 'تجاوز للميزانية',
    safeBudget: 'ضمن الحدود الآمنة',
    setPin: 'تعيين رمز سري للحساب',
    pinActive: 'الحساب محمي برمز PIN',
    exportTitle: 'تصدير التقارير المالية للأسرة',
    exportDesc: 'قم بتحميل وتصدير بيانات المصاريف بصيغ متعددة للطباعة والتحليل',
    exportPdf: 'تصدير تقرير PDF جاهز للطباعة',
    exportExcel: 'تصدير جدول Excel (XLSX)',
    exportCsv: 'تصدير ملف CSV',
    exportJson: 'تصدير نسخة احتياطية JSON',
    analytics: 'التحليلات والمقارنات الذكية',
    analyticsDesc: 'رسوم بيانية تفاعلية وتحليلات دقيقة لمصاريف الأسرة حسب الفئات والأفراد',
    manageMembers: 'إدارة أفراد الأسرة والميزانيات',
    manageMembersDesc: 'إضافة أعضاء، تحديد الأدوار، وتعيين سقف الميزانية الشهرية لكل فرد',
    addMember: 'إضافة فرد جديد للأسرة',
    memberName: 'اسم الفرد',
    memberRole: 'الدور في الأسرة',
    monthlyBudget: 'الميزانية الشهرية المخصصة',
    quickExpense: 'تسجيل مصروف سريع',
    quickIncome: 'تسجيل دخل سريع',
    allCategories: 'جميع الفئات',
    filterByCategory: 'تصفية حسب الفئة',
    clearFilters: 'مسح التصفية',
    noResults: 'لا توجد نتائج',
    addFirstTransaction: 'أضف أول معاملة لك الآن',
    beneficiaryAllFamily: 'الأسرة بالكامل',
    forMyself: 'لنفسي فقط',
    generalFamily: 'عام للأسرة',

    // Categories
    cat_food: 'طعام ومشتريات بقالة',
    cat_housing: 'سكن وإيجار',
    cat_utilities: 'فواتير وخدمات منزلية',
    cat_transport: 'مواصلات وبنزين وصيانة',
    cat_health: 'صحة ورعاية طبية وأدوية',
    cat_education: 'تعليم ومدارس ومستلزمات',
    cat_entertainment: 'ترفيه ورحلات ومطاعم',
    cat_shopping: 'تسوق وملابس وإلكترونيات',
    cat_personal: 'مصاريف شخصية ومصروف جيب',
    cat_debt: 'التزامات وأقساط وديون',
    cat_investments: 'ادخار واستثمار',
    cat_salary: 'راتب شهري',
    cat_business: 'أرباح وتجارة',
    cat_gift: 'مكافآت وهدايا وعيديات',
    cat_other: 'أخرى ومتنوعات',

    // Roles
    role_father: 'الأب (رب الأسرة)',
    role_mother: 'الأم',
    role_son: 'الابن',
    role_daughter: 'الابنة',
    role_grandfather: 'الجد',
    role_grandmother: 'الجدة',
    role_other: 'فرد آخر',

    // Payment Methods
    pm_cash: 'نقدي (كاش)',
    pm_card: 'بطاقة بنكية / مدى',
    pm_bank_transfer: 'تحويل بنكي',
    pm_digital_wallet: 'محفظة إلكترونية (Apple/STC Pay)',
    pm_other: 'طريقة أخرى',

    // UI Panel & Dashboard Keys
    founderControlPanel: 'لوحة تحكم مؤسس العائلة',
    previewMemberPage: 'معاينة صفحة العضو',
    founderModeDesc: 'أنت في وضع المؤسس مع وصول كامل لكافة العمليات والأفراد',
    fullPermissions: 'صلاحيات كاملة',
    analyticsTitle: 'تحليلات ومقارنات المصاريف',
    perMemberShare: 'حصة كل فرد',
    byCategory: 'حسب الفئة',
    dailyMovement: 'الحركة اليومية',
    memberExpenseRatio: 'نسبة مصاريف الأفراد',
    categoryDistribution: 'توزيع المصاريف حسب الفئات',
    topSpendingAreas: 'أعلى مجالات الإنفاق',
    selectMemberToView: 'اختر فرداً لمعاينة حسابه الشخصي',
    viewMemberTransactions: 'عرض معاملات الفرد',
    switchProfile: 'تبديل الملف الشخصي',
    allRecurringExpensesRecorded: 'تم تسجيل جميع الالتزامات الشهرية',
    myExpensesThisMonth: 'مصاريفي هذا الشهر',
    myIncomeThisMonth: 'دخلي هذا الشهر',
    myMonthlyCommitments: 'التزاماتي الشهرية',
    remainingBudget: 'الميزانية المتبقية',
    netBalance: 'صافي الرصيد',
    noBudgetSet: 'لم يتم تحديد ميزانية',
    manageRecurringDesc: 'إدارة وتتبع المصاريف والالتزامات الثابتة شهرياً',
    recordMonthlyCommitments: 'تسجيل الالتزامات الشهرية دفعة واحدة',
    pendingCommitmentsCount: 'التزامات شهرية معلقة',
    addRecurringCommitment: 'إضافة التزام شهري متكرر',
    noRecurringExpenses: 'لا توجد مصاريف متكررة مسجلة',
    memberBudgetsTracking: 'تتبع ميزانيات أفراد الأسرة',
    memberBudgetsTrackingDesc: 'متابعة الصرف الفعلي ومقارنته بالميزانية المحددة لكل فرد',
    memberExpensesOverview: 'نظرة عامة على مصاريف الأفراد',
    saveAsMonthlyRecurring: 'حفظ كمصروف شهري متكرر',
    recordExpenseDesc: 'تسجيل مصروف جديد للأسرة أو لأحد الأفراد',
    beneficiaryMember: 'المستفيد من المعاملة',
    whoPaid: 'الشخص الذي قام بالدفع',
    quickRecord: 'تسجيل سريع',
    quickAmounts: 'مبالغ سريعة',
    titlePlaceholder: 'مثال: مشتريات السوبرماركت، بنزين، إيجار...',
    descriptionPlaceholder: 'ملاحظات وتفاصيل إضافية (اختياري)...',
    titleRequired: 'يرجى كتابة عنوان المعاملة',
    amountRequired: 'يرجى إدخال مبلغ صحيح أكبر من الصفر',
    categoryRequired: 'يرجى اختيار الفئة المناسبة',
    memberRequired: 'يرجى تحديد الفرد المعني',
    addNewMember: 'إضافة عضو جديد للأسرة',
    memberSecurityPin: 'رمز PIN الشخصي للعضو',
    memberPinPlaceholder: '4 أرقام (اختياري)',
    selectAvatar: 'اختر الرمز التعبيري المناسب',
    pinMismatch: 'الرمزان غير متطابقين',
    invalidPin: 'الرمز السري غير صحيح',
    currentPin: 'الرمز السري الحالي',
    newPin: 'الرمز السري الجديد (4 أرقام)',
    confirmPin: 'تأكيد الرمز السري',
    saveChanges: 'حفظ التعديلات',
    confirmDelete: 'هل أنت متأكد من الحذف؟',
    confirm: 'تأكيد',
    printReport: 'طباعة التقرير',
    exportReport: 'تصدير التقرير',
    spent: 'مصروف',
    exceededBy: 'تجاوز بمقدار',
    budgetWarning: 'تنبيه: اقترب أو تجاوز الفرد ميزانيته الشهرية',
    customRoleTitle: 'المسمى المخصص',
    enterFounderPin: 'أدخل الرمز السري لمؤسس العائلة',
    founderPinSettings: 'إعدادات الرمز السري للمؤسس',
    founderPinDesc: 'قم بحماية لوحة المؤسس برمز سري من 4 أرقام لمنع دخول الأفراد الآخرين إليها',
    pinConfigured: 'الرمز السري مفعل ومحمي',
    pinNotConfigured: 'الرمز السري غير مفعل (الافتراضي: 1234)',
    pinLockNotice: 'الرجاء إدخال الرمز السري للمتابعة',
    lockoutNotice: 'تم إيقاف المحاولات مؤقتاً',
    seconds: 'ثانية',
    digits: 'أرقام',
    pinDigitsNotice: 'يجب أن يتكون الرمز السري من 4 أرقام',
    preview: 'معاينة',
    previewAccount: 'معاينة الحساب',
    other: 'أخرى',
    paused: 'موقوف مؤقتاً',
    dueDay: 'يوم الاستحقاق',
    dueForMonth: 'مستحق للشهر الحالي',
    addedForMonth: 'تمت إضافته للشهر الحالي',
    addForMonth: 'إضافة للشهر',
    day: 'يوم',
    editTransaction: 'تعديل المعاملة',
    descriptionOptional: 'الوصف (اختياري)',
    backup: 'نسخة احتياطية',
    unspecified: 'غير محدد',
    categories: 'الفئات',
    role: 'الدور',
    transactions: 'المعاملات',
    appTagline: 'إدارة ميزانية ومصاريف الأسرة بذكاء وخصوصية',
    cleanResetButton: 'تفريغ وتصفير البيانات (حساب نظيف)',
    cleanResetConfirm: 'هل أنت متأكد من تصفير الحساب؟ سيتم مسح أي بيانات تجريبية والبدء بحسابك الخاص فقط.',
    theme: 'المظهر',
    darkMode: 'الوضع الليلي (الداكن)',
    lightMode: 'الوضع النهاري (الفاتح)',
    toggleTheme: 'تبديل المظهر',
    switchToDarkMode: 'التحويل إلى الوضع الداكن',
    switchToLightMode: 'التحويل إلى الوضع الفاتح',
  },

  en: {
    // Brand & Main
    appName: 'Family Expenses',
    appSubtitle: 'Family Budget & Expense Management System',
    founder: 'Founder',
    founderMode: 'Founder Dashboard (Head of Family)',
    founderBadge: '👑 Founder',
    memberBadge: '👤 Family Member',
    memberPersonalView: 'Personal Account View',
    founderSubtitleFull: 'Founder Control Panel (Full management for all members)',
    memberSubtitleFull: 'Personal Account: My expenses and income only',
    welcome: 'Welcome',
    totalBalance: 'Net Balance',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    recurringMonthly: 'Recurring Expenses',
    addExpense: 'Add Expense',
    addIncome: 'Add Income',
    familyMembers: 'Family Members',
    recurringExpenses: 'Recurring Expenses',
    exportReports: 'Export Reports',
    changeLanguage: 'Change Language',
    changeCurrency: 'Change Currency',
    founderSecurityPin: 'Founder PIN Code',
    logout: 'Log Out',
    login: 'Log In',
    register: 'Create Account',
    allMembers: 'All Family Members',
    recentTransactions: 'Recent Transactions',
    searchPlaceholder: 'Search descriptions, beneficiaries, tags...',
    noTransactionsFound: 'No transactions recorded matching your search',
    filterBy: 'Filter by',
    all: 'All',
    expense: 'Expense',
    income: 'Income',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    customRange: 'Custom',
    category: 'Category',
    amount: 'Amount',
    payer: 'Payer',
    beneficiary: 'Beneficiary',
    paymentMethod: 'Payment Method',
    date: 'Date',
    notes: 'Notes',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    offline: 'Offline Mode',
    online: 'Cloud Connected',
    demo: 'Demo',
    synced: 'Cloud Synced',
    syncing: 'Syncing...',
    securityProtected: 'Secured by PIN & Cloud Protected',
    enterPin: 'Enter PIN Code',
    lockoutWarning: 'Input temporarily locked out due to repeated errors',
    languageSelectorTitle: 'Select Application Language for Family',
    languageSelectorSubtitle: 'Choose your preferred language for easy browsing & reports',
    currencySelectorTitle: 'Select Global System Currency',
    activeLanguage: 'Current Language',
    founderPanelTitle: 'Family Founder Dashboard (Master Control)',
    fullPrivileges: 'Full Access',
    founderPanelDesc: 'You are in Founder Mode: monitor all transactions, allocate budgets, and manage the entire family.',
    viewingAllMembers: 'You are currently viewing combined data for all family members',
    personalBannerTitle: 'Personal Account Dashboard',
    personalBannerDesc: 'You are in your independent personal view. Transactions recorded here reflect your budget and the family budget.',
    myTransactions: 'My Personal Transactions',
    myExpenses: 'My Expenses',
    myIncome: 'My Income',
    myBalance: 'My Net Balance',
    budgetLimit: 'Assigned Monthly Budget',
    spentSoFar: 'Spent So Far',
    remaining: 'Remaining',
    overBudget: 'Over Budget',
    safeBudget: 'Within Safe Limits',
    setPin: 'Set Personal PIN Code',
    pinActive: 'Account is PIN Protected',
    exportTitle: 'Export Family Financial Reports',
    exportDesc: 'Download and export expense records in multiple formats for print and analysis',
    exportPdf: 'Export Print-Ready PDF Report',
    exportExcel: 'Export Excel Sheet (XLSX)',
    exportCsv: 'Export CSV File',
    exportJson: 'Export JSON Backup',
    analytics: 'Smart Analytics & Insights',
    analyticsDesc: 'Interactive charts and precise expense breakdown by categories and members',
    manageMembers: 'Manage Family Members & Budgets',
    manageMembersDesc: 'Add members, set roles, and assign monthly budget caps',
    addMember: 'Add New Family Member',
    memberName: 'Member Name',
    memberRole: 'Family Role',
    monthlyBudget: 'Allocated Monthly Budget',
    quickExpense: 'Quick Expense Entry',
    quickIncome: 'Quick Income Entry',
    allCategories: 'All Categories',
    filterByCategory: 'Filter by Category',
    clearFilters: 'Clear Filters',
    noResults: 'No results found',
    addFirstTransaction: 'Add your first transaction now',
    beneficiaryAllFamily: 'Whole Family',
    forMyself: 'For Myself',
    generalFamily: 'General Family',

    // Categories
    cat_food: 'Food & Groceries',
    cat_housing: 'Housing & Rent',
    cat_utilities: 'Utilities & Bills',
    cat_transport: 'Transport & Fuel',
    cat_health: 'Health & Medical',
    cat_education: 'Education & Schools',
    cat_entertainment: 'Entertainment & Dining',
    cat_shopping: 'Shopping & Clothes',
    cat_personal: 'Personal & Pocket Money',
    cat_debt: 'Debts & Installments',
    cat_investments: 'Savings & Investments',
    cat_salary: 'Monthly Salary',
    cat_business: 'Business & Profits',
    cat_gift: 'Rewards & Gifts',
    cat_other: 'Other & Miscellaneous',

    // Roles
    role_father: 'Father (Head of Family)',
    role_mother: 'Mother',
    role_son: 'Son',
    role_daughter: 'Daughter',
    role_grandfather: 'Grandfather',
    role_grandmother: 'Grandmother',
    role_other: 'Other Member',

    // Payment Methods
    pm_cash: 'Cash',
    pm_card: 'Bank / Debit Card',
    pm_bank_transfer: 'Bank Transfer',
    pm_digital_wallet: 'Digital Wallet (Apple/STC Pay)',
    pm_other: 'Other Method',

    // UI Panel & Dashboard Keys
    founderControlPanel: 'Family Founder Control Panel',
    previewMemberPage: 'Preview Member Page',
    founderModeDesc: 'You are in Founder Mode with full access to all transactions and members',
    fullPermissions: 'Full Permissions',
    analyticsTitle: 'Expense Analytics & Comparisons',
    perMemberShare: 'Per Member Share',
    byCategory: 'By Category',
    dailyMovement: 'Daily Movement',
    memberExpenseRatio: 'Member Expense Ratio',
    categoryDistribution: 'Expense Distribution by Category',
    topSpendingAreas: 'Top Spending Areas',
    selectMemberToView: 'Select a member to preview their personal account',
    viewMemberTransactions: 'View Member Transactions',
    switchProfile: 'Switch Profile',
    allRecurringExpensesRecorded: 'All monthly recurring commitments are recorded',
    myExpensesThisMonth: 'My Expenses This Month',
    myIncomeThisMonth: 'My Income This Month',
    myMonthlyCommitments: 'My Monthly Commitments',
    remainingBudget: 'Remaining Budget',
    netBalance: 'Net Balance',
    noBudgetSet: 'No budget set',
    manageRecurringDesc: 'Manage and track fixed monthly recurring commitments',
    recordMonthlyCommitments: 'Record All Monthly Commitments',
    pendingCommitmentsCount: 'Pending Monthly Commitments',
    addRecurringCommitment: 'Add Recurring Commitment',
    noRecurringExpenses: 'No recurring expenses registered',
    memberBudgetsTracking: 'Member Budgets Tracking',
    memberBudgetsTrackingDesc: 'Monitor actual spending against assigned budget caps',
    memberExpensesOverview: 'Member Expenses Overview',
    saveAsMonthlyRecurring: 'Save as Monthly Recurring',
    recordExpenseDesc: 'Record new expense for family or member',
    beneficiaryMember: 'Beneficiary Member',
    whoPaid: 'Who Paid',
    quickRecord: 'Quick Entry',
    quickAmounts: 'Quick Amounts',
    titlePlaceholder: 'e.g., Grocery shopping, fuel, rent...',
    descriptionPlaceholder: 'Notes & additional details (optional)...',
    titleRequired: 'Please enter transaction title',
    amountRequired: 'Please enter a valid amount greater than 0',
    categoryRequired: 'Please select a category',
    memberRequired: 'Please select a family member',
    addNewMember: 'Add New Family Member',
    memberSecurityPin: 'Member Personal PIN Code',
    memberPinPlaceholder: '4 digits (optional)',
    selectAvatar: 'Choose Avatar Emoji',
    pinMismatch: 'PINs do not match',
    invalidPin: 'Invalid PIN Code',
    currentPin: 'Current PIN',
    newPin: 'New PIN (4 digits)',
    confirmPin: 'Confirm PIN',
    saveChanges: 'Save Changes',
    confirmDelete: 'Are you sure you want to delete?',
    confirm: 'Confirm',
    printReport: 'Print Report',
    exportReport: 'Export Report',
    spent: 'Spent',
    exceededBy: 'Exceeded by',
    budgetWarning: 'Warning: Member reached or exceeded monthly budget',
    customRoleTitle: 'Custom Title',
    enterFounderPin: 'Enter Founder PIN Code',
    founderPinSettings: 'Founder PIN Settings',
    founderPinDesc: 'Protect Founder Panel with a 4-digit PIN to prevent unauthorized member access',
    pinConfigured: 'PIN is Active & Protected',
    pinNotConfigured: 'PIN is Not Configured (Default: 1234)',
    pinLockNotice: 'Please enter PIN to proceed',
    lockoutNotice: 'Attempts temporarily locked',
    seconds: 'seconds',
    digits: 'digits',
    pinDigitsNotice: 'PIN must be 4 digits',
    preview: 'Preview',
    previewAccount: 'Preview Account',
    other: 'Other',
    paused: 'Paused',
    dueDay: 'Due Day',
    dueForMonth: 'Due for this month',
    addedForMonth: 'Recorded for this month',
    addForMonth: 'Record for Month',
    day: 'day',
    editTransaction: 'Edit Transaction',
    descriptionOptional: 'Description (Optional)',
    backup: 'Backup',
    unspecified: 'Unspecified',
    categories: 'Categories',
    role: 'Role',
    transactions: 'Transactions',
    appTagline: 'Smart & private family budget and expense tracker',
    cleanResetButton: 'Reset to Clean Account',
    cleanResetConfirm: 'Are you sure you want to reset your account? Any demo data will be purged and only your registered founder account will remain.',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    toggleTheme: 'Toggle Theme',
    switchToDarkMode: 'Switch to Dark Mode',
    switchToLightMode: 'Switch to Light Mode',
  },

  fr: {
    appName: 'Dépenses Familiales',
    appSubtitle: 'Gestion de Budget et Dépenses Familiales',
    founder: 'Fondateur',
    founderMode: 'Tableau de bord Fondateur',
    founderBadge: '👑 Fondateur',
    memberBadge: '👤 Membre',
    memberPersonalView: 'Espace Personnel',
    founderSubtitleFull: 'Panneau de contrôle Fondateur (Gestion complète)',
    memberSubtitleFull: 'Compte personnel : mes dépenses et revenus uniquement',
    welcome: 'Bienvenue',
    totalBalance: 'Solde Net',
    totalIncome: 'Revenus Totaux',
    totalExpenses: 'Dépenses Totales',
    recurringMonthly: 'Dépenses Récurrentes',
    addExpense: 'Ajouter Dépense',
    addIncome: 'Ajouter Revenu',
    familyMembers: 'Membres de la Famille',
    recurringExpenses: 'Dépenses Récurrentes',
    exportReports: 'Exporter Rapports',
    changeLanguage: 'Changer de Langue',
    changeCurrency: 'Changer de Devise',
    founderSecurityPin: 'Code PIN Fondateur',
    logout: 'Déconnexion',
    login: 'Connexion',
    register: 'Créer un Compte',
    allMembers: 'Tous les Membres',
    recentTransactions: 'Transactions Récentes',
    searchPlaceholder: 'Rechercher description, bénéficiaire, tags...',
    noTransactionsFound: 'Aucune transaction enregistrée',
    filterBy: 'Filtrer par',
    all: 'Tous',
    expense: 'Dépense',
    income: 'Revenu',
    today: "Aujourd'hui",
    yesterday: 'Hier',
    thisWeek: 'Cette Semaine',
    thisMonth: 'Ce Mois',
    thisYear: 'Cette Année',
    customRange: 'Personnalisé',
    category: 'Catégorie',
    amount: 'Montant',
    payer: 'Payeur',
    beneficiary: 'Bénéficiaire',
    paymentMethod: 'Moyen de Paiement',
    date: 'Date',
    notes: 'Notes',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    close: 'Fermer',
    offline: 'Mode Hors Ligne',
    online: 'Connecté au Cloud',
    demo: 'Démo',
    synced: 'Synchronisé',
    syncing: 'Synchronisation...',
    securityProtected: 'Sécurisé par PIN',
    enterPin: 'Entrez le code PIN',
    lockoutWarning: 'Bloqué temporairement',
    languageSelectorTitle: "Choisir la Langue de l'Application",
    languageSelectorSubtitle: 'Sélectionnez votre langue préférée pour naviguer facilement',
    currencySelectorTitle: 'Choisir la Devise Mondiale',
    activeLanguage: 'Langue Actuelle',
    founderPanelTitle: 'Tableau de bord Fondateur (Contrôle Total)',
    fullPrivileges: 'Accès Complet',
    founderPanelDesc: 'Mode Fondateur : visualisez tout, allouez les budgets et gérez la famille.',
    viewingAllMembers: 'Vous visualisez les données de tous les membres',
    personalBannerTitle: 'Tableau de bord Personnel',
    personalBannerDesc: 'Espace personnel indépendant. Vos dépenses reflètent vos finances et celles de la famille.',
    myTransactions: 'Mes Transactions',
    myExpenses: 'Mes Dépenses',
    myIncome: 'Mes Revenus',
    myBalance: 'Mon Solde',
    budgetLimit: 'Budget Mensuel Alloué',
    spentSoFar: 'Dépensé',
    remaining: 'Restant',
    overBudget: 'Budget Dépassé',
    safeBudget: 'Dans la limite du budget',
    setPin: 'Définir un code PIN',
    pinActive: 'Compte protégé par PIN',
    exportTitle: 'Exporter les Rapports',
    exportDesc: 'Téléchargez vos transactions sous plusieurs formats',
    exportPdf: 'Exporter en PDF',
    exportExcel: 'Exporter en Excel (XLSX)',
    exportCsv: 'Exporter en CSV',
    exportJson: 'Sauvegarde JSON',
    analytics: 'Analyses & Statistiques',
    analyticsDesc: 'Graphiques interactifs et répartition des dépenses',
    manageMembers: 'Gérer les Membres',
    manageMembersDesc: 'Ajouter des membres et définir les plafonds de budget',
    addMember: 'Ajouter un membre',
    memberName: 'Nom du membre',
    memberRole: 'Rôle dans la famille',
    monthlyBudget: 'Budget mensuel',
    quickExpense: 'Dépense Rapide',
    quickIncome: 'Revenu Rapide',
    allCategories: 'Toutes les catégories',
    filterByCategory: 'Filtrer par catégorie',
    clearFilters: 'Effacer les filtres',
    noResults: 'Aucun résultat',
    addFirstTransaction: 'Ajoutez votre première transaction',
    beneficiaryAllFamily: 'Toute la famille',
    forMyself: 'Pour moi-même',
    generalFamily: 'Général Famille',

    cat_food: 'Nourriture & Épicerie',
    cat_housing: 'Logement & Loyer',
    cat_utilities: 'Factures & Services',
    cat_transport: 'Transport & Carburant',
    cat_health: 'Santé & Médicaments',
    cat_education: 'Éducation & Fournitures',
    cat_entertainment: 'Loisirs & Restaurants',
    cat_shopping: 'Shopping & Vêtements',
    cat_personal: 'Dépenses Personnelles',
    cat_debt: 'Dettes & Crédits',
    cat_investments: 'Épargne & Investissements',
    cat_salary: 'Salaire Mensuel',
    cat_business: 'Affaires & Commerce',
    cat_gift: 'Cadeaux & Primes',
    cat_other: 'Autres & Divers',

    role_father: 'Père (Chef de famille)',
    role_mother: 'Mère',
    role_son: 'Fils',
    role_daughter: 'Fille',
    role_grandfather: 'Grand-père',
    role_grandmother: 'Grand-mère',
    role_other: 'Autre membre',

    pm_cash: 'Espèces (Cash)',
    pm_card: 'Carte Bancaire',
    pm_bank_transfer: 'Virement Bancaire',
    pm_digital_wallet: 'Portefeuille Électronique',
    pm_other: 'Autre mode',
  },

  tr: {
    appName: 'Aile Giderleri',
    appSubtitle: 'Aile Bütçesi ve Gider Takip Sistemi',
    founder: 'Kurucu',
    founderMode: 'Kurucu Paneli',
    founderBadge: '👑 Kurucu',
    memberBadge: '👤 Aile Üyesi',
    memberPersonalView: 'Kişisel Hesap Paneli',
    founderSubtitleFull: 'Kurucu Yönetim Paneli (Tüm aile üyelerini yönet)',
    memberSubtitleFull: 'Kişisel hesap: Yalnızca kendi gelir ve giderlerim',
    welcome: 'Hoş Geldiniz',
    totalBalance: 'Net Bakiye',
    totalIncome: 'Toplam Gelir',
    totalExpenses: 'Toplam Gider',
    recurringMonthly: 'Düzenli Giderler',
    addExpense: 'Gider Ekle',
    addIncome: 'Gelir Ekle',
    familyMembers: 'Aile Üyeleri',
    recurringExpenses: 'Düzenli Giderler',
    exportReports: 'Raporları Dışa Aktar',
    changeLanguage: 'Dili Değiştir',
    changeCurrency: 'Para Birimini Değiştir',
    founderSecurityPin: 'Kurucu PIN Kodu',
    logout: 'Çıkış Yap',
    login: 'Giriş Yap',
    register: 'Hesap Oluştur',
    allMembers: 'Tüm Aile Üyeleri',
    recentTransactions: 'Son İşlemler',
    searchPlaceholder: 'Açıklama, kişi veya etiket ara...',
    noTransactionsFound: 'Eşleşen işlem bulunamadı',
    filterBy: 'Filtrele',
    all: 'Tümü',
    expense: 'Gider',
    income: 'Gelir',
    today: 'Bugün',
    yesterday: 'Dün',
    thisWeek: 'Bu Hafta',
    thisMonth: 'Bu Ay',
    thisYear: 'Bu Yıl',
    customRange: 'Özel',
    category: 'Kategori',
    amount: 'Tutar',
    payer: 'Ödeyen',
    beneficiary: 'Faydalanan',
    paymentMethod: 'Ödeme Yöntemi',
    date: 'Tarih',
    notes: 'Notlar',
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    edit: 'Düzenle',
    close: 'Kapat',
    offline: 'Çevrimdışı Mod',
    online: 'Bulut Bağlantılı',
    demo: 'Demo',
    synced: 'Senkronize Edildi',
    syncing: 'Senkronize ediliyor...',
    securityProtected: 'PIN Korumalı',
    enterPin: 'PIN Kodunu Girin',
    lockoutWarning: 'Geçici olarak kilitlendi',
    languageSelectorTitle: 'Uygulama Dilini Seçin',
    languageSelectorSubtitle: 'Arayüzü kolay kullanmak için dilinizi seçin',
    currencySelectorTitle: 'Sistem Para Birimini Seçin',
    activeLanguage: 'Geçerli Dil',
    founderPanelTitle: 'Aile Kurucu Kontrol Paneli',
    fullPrivileges: 'Tam Yetki',
    founderPanelDesc: 'Kurucu modundasınız: Tüm işlemleri görün, bütçeleri yönetin.',
    viewingAllMembers: 'Tüm aile üyelerinin verilerini görüntülüyorsunuz',
    personalBannerTitle: 'Kişisel Hesap Paneli',
    personalBannerDesc: 'Kişisel alanınızdasınız. Kaydedilen işlemler hem sizin hem de ailenin bütçesini etkiler.',
    myTransactions: 'Kişisel İşlemlerim',
    myExpenses: 'Giderlerim',
    myIncome: 'Gelirlerim',
    myBalance: 'Net Bakiyem',
    budgetLimit: 'Aylık Bütçe Limiti',
    spentSoFar: 'Harcanan',
    remaining: 'Kalan',
    overBudget: 'Bütçe Aşıldı',
    safeBudget: 'Bütçe Dahilinde',
    setPin: 'PIN Kodu Belirle',
    pinActive: 'Hesap PIN Korumalı',
    exportTitle: 'Finansal Raporları İndir',
    exportDesc: 'Kayıtları Excel, PDF veya CSV formatında indirin',
    exportPdf: 'PDF Raporu İndir',
    exportExcel: 'Excel (XLSX) İndir',
    exportCsv: 'CSV İndir',
    exportJson: 'JSON Yedek İndir',
    analytics: 'Akıllı Analiz ve Grafikler',
    analyticsDesc: 'Kategorilere ve kişilere göre harcama dağılımı',
    manageMembers: 'Aile Üyeleri ve Bütçeler',
    manageMembersDesc: 'Üye ekleyin ve aylık bütçe limitlerini belirleyin',
    addMember: 'Yeni Üye Ekle',
    memberName: 'Üye Adı',
    memberRole: 'Aile Rolü',
    monthlyBudget: 'Aylık Bütçe',
    quickExpense: 'Hızlı Gider',
    quickIncome: 'Hızlı Gelir',
    allCategories: 'Tüm Kategoriler',
    filterByCategory: 'Kategoriye Göre Filtrele',
    clearFilters: 'Filtreleri Temizle',
    noResults: 'Sonuç bulunamadı',
    addFirstTransaction: 'İlk işleminizi hemen ekleyin',
    beneficiaryAllFamily: 'Tüm Aile',
    forMyself: 'Yalnızca Kendim',
    generalFamily: 'Genel Aile',

    cat_food: 'Yiyecek ve Market',
    cat_housing: 'Konut ve Kira',
    cat_utilities: 'Faturalar ve Hizmetler',
    cat_transport: 'Ulaşım ve Yakıt',
    cat_health: 'Sağlık ve İlaç',
    cat_education: 'Eğitim ve Okul',
    cat_entertainment: 'Eğlence ve Restoran',
    cat_shopping: 'Alışveriş ve Giyim',
    cat_personal: 'Kişisel Harçlık',
    cat_debt: 'Borçlar ve Taksitler',
    cat_investments: 'Tasarruf ve Yatırım',
    cat_salary: 'Aylık Maaş',
    cat_business: 'Ticaret ve İş',
    cat_gift: 'Hediyeler ve İkramiyeler',
    cat_other: 'Diğer Harcamalar',

    role_father: 'Baba (Aile Reisi)',
    role_mother: 'Anne',
    role_son: 'Erkek Çocuk',
    role_daughter: 'Kız Çocuk',
    role_grandfather: 'Dede',
    role_grandmother: 'Büyükanne',
    role_other: 'Diğer Üye',

    pm_cash: 'Nakit (Cash)',
    pm_card: 'Banka Kartı / Kredi Kartı',
    pm_bank_transfer: 'Banka Havalesi',
    pm_digital_wallet: 'Dijital Cüzdan',
    pm_other: 'Diğer Yöntem',
  },

  es: {
    appName: 'Gastos Familiares',
    appSubtitle: 'Sistema de Gestión de Presupuesto y Gastos',
    founder: 'Fundador',
    founderMode: 'Panel del Fundador',
    founderBadge: '👑 Fundador',
    memberBadge: '👤 Miembro',
    memberPersonalView: 'Vista Personal',
    founderSubtitleFull: 'Panel de Control del Fundador (Gestión Total)',
    memberSubtitleFull: 'Cuenta personal: Solo mis gastos e ingresos',
    welcome: 'Bienvenido',
    totalBalance: 'Balance Neto',
    totalIncome: 'Ingresos Totales',
    totalExpenses: 'Gastos Totales',
    recurringMonthly: 'Gastos Recurrentes',
    addExpense: 'Añadir Gasto',
    addIncome: 'Añadir Ingreso',
    familyMembers: 'Miembros de la Familia',
    recurringExpenses: 'Gastos Recurrentes',
    exportReports: 'Exportar Informes',
    changeLanguage: 'Cambiar Idioma',
    changeCurrency: 'Cambiar Moneda',
    founderSecurityPin: 'Código PIN del Fundador',
    logout: 'Cerrar Sesión',
    login: 'Iniciar Sesión',
    register: 'Crear Cuenta',
    allMembers: 'Todos los Miembros',
    recentTransactions: 'Transacciones Recientes',
    searchPlaceholder: 'Buscar descripción, miembro, etiquetas...',
    noTransactionsFound: 'No se encontraron transacciones',
    filterBy: 'Filtrar por',
    all: 'Todos',
    expense: 'Gasto',
    income: 'Ingreso',
    today: 'Hoy',
    yesterday: 'Ayer',
    thisWeek: 'Esta Semana',
    thisMonth: 'Este Mes',
    thisYear: 'Este Año',
    customRange: 'Personalizado',
    category: 'Categoría',
    amount: 'Monto',
    payer: 'Pagador',
    beneficiary: 'Beneficiario',
    paymentMethod: 'Método de Pago',
    date: 'Fecha',
    notes: 'Notas',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    close: 'Cerrar',
    offline: 'Modo sin conexión',
    online: 'Conectado a la nube',
    demo: 'Demo',
    synced: 'Sincronizado',
    syncing: 'Sincronizando...',
    securityProtected: 'Protegido por PIN',
    enterPin: 'Introduzca el código PIN',
    lockoutWarning: 'Bloqueado temporalmente',
    languageSelectorTitle: 'Seleccionar Idioma de la Aplicación',
    languageSelectorSubtitle: 'Elija su idioma preferido para navegar fácilmente',
    currencySelectorTitle: 'Seleccionar Moneda del Sistema',
    activeLanguage: 'Idioma Actual',
    founderPanelTitle: 'Panel del Fundador Familiar',
    fullPrivileges: 'Acceso Total',
    founderPanelDesc: 'Modo Fundador: supervise transacciones, asigne presupuestos y gestione la familia.',
    viewingAllMembers: 'Viendo datos combinados de todos los miembros',
    personalBannerTitle: 'Panel de Cuenta Personal',
    personalBannerDesc: 'Espacio personal independiente.',
    myTransactions: 'Mis Transacciones',
    myExpenses: 'Mis Gastos',
    myIncome: 'Mis Ingresos',
    myBalance: 'Mi Saldo Neto',
    budgetLimit: 'Presupuesto Asignado',
    spentSoFar: 'Gastado',
    remaining: 'Restante',
    overBudget: 'Presupuesto Superado',
    safeBudget: 'Dentro del Límite',
    setPin: 'Configurar PIN',
    pinActive: 'Cuenta protegida con PIN',
    exportTitle: 'Exportar Informes Financieros',
    exportDesc: 'Descargue registros en PDF, Excel o CSV',
    exportPdf: 'Exportar en PDF',
    exportExcel: 'Exportar en Excel (XLSX)',
    exportCsv: 'Exportar en CSV',
    exportJson: 'Copia de Seguridad JSON',
    analytics: 'Análisis y Estadísticas',
    analyticsDesc: 'Gráficos interactivos de gastos',
    manageMembers: 'Gestionar Miembros',
    manageMembersDesc: 'Añadir miembros y fijar presupuestos',
    addMember: 'Añadir Miembro',
    memberName: 'Nombre del Miembro',
    memberRole: 'Rol Familiar',
    monthlyBudget: 'Presupuesto Mensual',
    quickExpense: 'Gasto Rápido',
    quickIncome: 'Ingreso Rápido',
    allCategories: 'Todas las Categorías',
    filterByCategory: 'Filtrar por Categoría',
    clearFilters: 'Limpiar Filtros',
    noResults: 'Sin resultados',
    addFirstTransaction: 'Añade tu primera transacción',
    beneficiaryAllFamily: 'Toda la Familia',
    forMyself: 'Para Mí',
    generalFamily: 'General Familiar',

    cat_food: 'Comida y Supermercado',
    cat_housing: 'Vivienda y Alquiler',
    cat_utilities: 'Servicios y Facturas',
    cat_transport: 'Transporte y Combustible',
    cat_health: 'Salud y Farmacia',
    cat_education: 'Educación y Colegio',
    cat_entertainment: 'Ocio y Restaurantes',
    cat_shopping: 'Compras y Ropa',
    cat_personal: 'Gastos Personales',
    cat_debt: 'Deudas y Créditos',
    cat_investments: 'Ahorro e Inversión',
    cat_salary: 'Salario Mensual',
    cat_business: 'Negocios y Comercio',
    cat_gift: 'Regalos y Premios',
    cat_other: 'Otros Gastos',

    role_father: 'Padre (Cabeza de familia)',
    role_mother: 'Madre',
    role_son: 'Hijo',
    role_daughter: 'Hija',
    role_grandfather: 'Abuelo',
    role_grandmother: 'Abuela',
    role_other: 'Otro Miembro',

    pm_cash: 'Efectivo',
    pm_card: 'Tarjeta Bancaria',
    pm_bank_transfer: 'Transferencia Bancaria',
    pm_digital_wallet: 'Billetera Digital',
    pm_other: 'Otro Método',
  },

  ur: {
    appName: 'خاندانی اخراجات',
    appSubtitle: 'خاندانی بجٹ اور اخراجات کا نظام',
    founder: 'بانی (سربراہ)',
    founderMode: 'بانی کا ڈیش بورڈ (سربراہ)',
    founderBadge: '👑 بانی',
    memberBadge: '👤 فیملی ممبر',
    memberPersonalView: 'ذاتی اکاؤنٹ ویو',
    founderSubtitleFull: 'بانی کنٹرول پینل (تمام ممبران کا مکمل کنٹرول)',
    memberSubtitleFull: 'ذاتی اکاؤنٹ: صرف میری آمدنی اور اخراجات',
    welcome: 'خوش آمدید',
    totalBalance: 'کل بیلنس',
    totalIncome: 'کل آمدنی',
    totalExpenses: 'کل اخراجات',
    recurringMonthly: 'ماہانہ اخراجات',
    addExpense: 'خرچہ شامل کریں',
    addIncome: 'آمدنی شامل کریں',
    familyMembers: 'خاندان کے افراد',
    recurringExpenses: 'ماہانہ بل اور اخراجات',
    exportReports: 'رپورٹ ڈاؤن لوڈ کریں',
    changeLanguage: 'زبان تبدیل کریں',
    changeCurrency: 'کرنسی تبدیل کریں',
    founderSecurityPin: 'سربراہ کا خفیہ پن کوڈ',
    logout: 'لاگ آؤٹ',
    login: 'لاگ ان',
    register: 'نیا اکاؤنٹ بنائیں',
    allMembers: 'تمام فیملی ممبران',
    recentTransactions: 'حالیہ لین دین',
    searchPlaceholder: 'تفصیل، شخص، یا ٹیگز تلاش کریں...',
    noTransactionsFound: 'کوئی ریکارڈ نہیں ملا',
    filterBy: 'فلٹر کریں',
    all: 'تمام',
    expense: 'خرچہ',
    income: 'آمدنی',
    today: 'آج',
    yesterday: 'کل',
    thisWeek: 'اس ہفتے',
    thisMonth: 'اس مہینے',
    thisYear: 'اس سال',
    customRange: 'مخصوص تاریخ',
    category: 'کیٹیگری',
    amount: 'رقم',
    payer: 'ادا کرنے والا',
    beneficiary: 'استفادہ کنندہ',
    paymentMethod: 'ادائیگی کا طریقہ',
    date: 'تاریخ',
    notes: 'نوٹس',
    save: 'محفوظ کریں',
    cancel: 'منسوخ',
    delete: 'حذف کریں',
    edit: 'ترمیم',
    close: 'بند کریں',
    offline: 'آف لائن موڈ',
    online: 'کلاؤڈ سے منسلک',
    demo: 'آزمائشی',
    synced: 'ہم آہنگ ہو گیا',
    syncing: 'ہم آہنگی جاری ہے...',
    securityProtected: 'پن کوڈ سے محفوظ',
    enterPin: 'پن کوڈ درج کریں',
    lockoutWarning: 'عارضی طور پر لاک ہو گیا',
    languageSelectorTitle: 'ایپلیکیشن کی زبان منتخب کریں',
    languageSelectorSubtitle: 'اپنی پسندیدہ زبان کا انتخاب کریں',
    currencySelectorTitle: 'کرنسی منتخب کریں',
    activeLanguage: 'موجودہ زبان',
    founderPanelTitle: 'خاندانی سربراہ کنٹرول پینل',
    fullPrivileges: 'مکمل اختیارات',
    founderPanelDesc: 'آپ بانی موڈ میں ہیں: تمام لین دین، بجٹ اور فیملی ممبرز کا انتظام کریں۔',
    viewingAllMembers: 'آپ تمام فیملی ممبرز کا مجموعی ڈیٹا دیکھ رہے ہیں',
    personalBannerTitle: 'ذاتی اکاؤنٹ ڈیش بورڈ',
    personalBannerDesc: 'آپ اپنے آزاد ذاتی اکاؤنٹ میں ہیں۔',
    myTransactions: 'میرے ذاتی لین دین',
    myExpenses: 'میرے اخراجات',
    myIncome: 'میری آمدنی',
    myBalance: 'میرا کل بیلنس',
    budgetLimit: 'ماہانہ بجٹ کی حد',
    spentSoFar: 'اب تک کا خرچ',
    remaining: 'باقی رقم',
    overBudget: 'بجٹ سے زیادہ خرچ',
    safeBudget: 'بجٹ کے اندر',
    setPin: 'پن کوڈ لگائیں',
    pinActive: 'اکاؤنٹ پن سے محفوظ ہے',
    exportTitle: 'رپورٹس برآمد کریں',
    exportDesc: 'ریکارڈز کو پی ڈی ایف یا ایکسل میں ڈاؤن لوڈ کریں',
    exportPdf: 'پی ڈی ایف رپورٹ برآمد کریں',
    exportExcel: 'ایکسل شیٹ (XLSX)',
    exportCsv: 'سی ایس وی فائل',
    exportJson: 'بیک اپ فائل',
    analytics: 'تجزیات اور چارٹس',
    analyticsDesc: 'تفصیلی چارٹس اور اخراجات کا تجزیہ',
    manageMembers: 'ممبران کا انتظام',
    manageMembersDesc: 'نئے ممبرز شامل کریں اور بجٹ مقرر کریں',
    addMember: 'نیا ممبر شامل کریں',
    memberName: 'ممبر کا نام',
    memberRole: 'خاندانی رشتہ',
    monthlyBudget: 'ماہانہ بجٹ',
    quickExpense: 'فوری خرچہ',
    quickIncome: 'فوری آمدنی',
    allCategories: 'تمام کیٹیگریز',
    filterByCategory: 'کیٹیگری کے لحاظ سے فلٹر',
    clearFilters: 'فلٹر ختم کریں',
    noResults: 'کوئی نتیجہ نہیں ملا',
    addFirstTransaction: 'پہلا لین دین شامل کریں',
    beneficiaryAllFamily: 'پورا خاندان',
    forMyself: 'صرف میرے لیے',
    generalFamily: 'عام خاندانی',

    cat_food: 'کھانا اور راشن',
    cat_housing: 'رہائش اور کرایہ',
    cat_utilities: 'بلز اور یوٹیلیٹیز',
    cat_transport: 'ٹرانسپورٹ اور پیٹرول',
    cat_health: 'صحت اور ادویات',
    cat_education: 'تعلیم اور اسکول',
    cat_entertainment: 'تفریح اور ریسٹورنٹ',
    cat_shopping: 'شاپنگ اور کپڑے',
    cat_personal: 'ذاتی اخراجات',
    cat_debt: 'قرض اور اقساط',
    cat_investments: 'بچت اور سرمایہ کاری',
    cat_salary: 'ماہانہ تنخواہ',
    cat_business: 'کاروبار اور منافع',
    cat_gift: 'تحائف اور انعامات',
    cat_other: 'دیگر متفرق',

    role_father: 'والد (سربراہ)',
    role_mother: 'والدہ',
    role_son: 'بیٹا',
    role_daughter: 'بیٹی',
    role_grandfather: 'دادا/نانا',
    role_grandmother: 'دادی/نانی',
    role_other: 'دیگر ممبر',

    pm_cash: 'نقد (کیش)',
    pm_card: 'بینک کارڈ',
    pm_bank_transfer: 'بینک ٹرانسفر',
    pm_digital_wallet: 'ڈیجیٹل والیٹ',
    pm_other: 'دیگر طریقہ',
  },

  de: {
    appName: 'Familienausgaben',
    appSubtitle: 'Familienbudget- und Ausgabenverwaltung',
    founder: 'Gründer',
    founderMode: 'Gründer-Dashboard',
    founderBadge: '👑 Gründer',
    memberBadge: '👤 Mitglied',
    memberPersonalView: 'Persönliche Ansicht',
    founderSubtitleFull: 'Gründer-Kontrollzentrum (Volle Verwaltung)',
    memberSubtitleFull: 'Persönliches Konto: Nur meine Einnahmen und Ausgaben',
    welcome: 'Willkommen',
    totalBalance: 'Nettosaldo',
    totalIncome: 'Gesamteinnahmen',
    totalExpenses: 'Gesamtausgaben',
    recurringMonthly: 'Wiederkehrende Ausgaben',
    addExpense: 'Ausgabe hinzufügen',
    addIncome: 'Einnahme hinzufügen',
    familyMembers: 'Familienmitglieder',
    recurringExpenses: 'Wiederkehrende Ausgaben',
    exportReports: 'Berichte exportieren',
    changeLanguage: 'Sprache ändern',
    changeCurrency: 'Währung ändern',
    founderSecurityPin: 'Gründer-PIN',
    logout: 'Abmelden',
    login: 'Anmelden',
    register: 'Konto erstellen',
    allMembers: 'Alle Mitglieder',
    recentTransactions: 'Letzte Transaktionen',
    searchPlaceholder: 'Beschreibung, Mitglied suchen...',
    noTransactionsFound: 'Keine Transaktionen gefunden',
    filterBy: 'Filtern nach',
    all: 'Alle',
    expense: 'Ausgabe',
    income: 'Einnahme',
    today: 'Heute',
    yesterday: 'Gestern',
    thisWeek: 'Diese Woche',
    thisMonth: 'Dieser Monat',
    thisYear: 'Dieses Jahr',
    customRange: 'Benutzerdefiniert',
    category: 'Kategorie',
    amount: 'Betrag',
    payer: 'Zahler',
    beneficiary: 'Empfänger',
    paymentMethod: 'Zahlungsmethode',
    date: 'Datum',
    notes: 'Notizen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    close: 'Schließen',
    offline: 'Offline-Modus',
    online: 'Online',
    demo: 'Demo',
    synced: 'Synchronisiert',
    syncing: 'Synchronisiere...',
    securityProtected: 'PIN-geschützt',
    enterPin: 'PIN eingeben',
    lockoutWarning: 'Vorübergehend gesperrt',
    languageSelectorTitle: 'App-Sprache auswählen',
    languageSelectorSubtitle: 'Wählen Sie Ihre bevorzugte Sprache',
    currencySelectorTitle: 'Währung auswählen',
    activeLanguage: 'Aktuelle Sprache',
    founderPanelTitle: 'Gründer-Kontrollzentrum',
    fullPrivileges: 'Voller Zugriff',
    founderPanelDesc: 'Sie sind im Gründer-Modus.',
    viewingAllMembers: 'Daten aller Familienmitglieder',
    personalBannerTitle: 'Persönliches Dashboard',
    personalBannerDesc: 'Ihr persönlicher Bereich.',
    myTransactions: 'Meine Transaktionen',
    myExpenses: 'Meine Ausgaben',
    myIncome: 'Meine Einnahmen',
    myBalance: 'Mein Saldo',
    budgetLimit: 'Monatsbudget',
    spentSoFar: 'Bisher ausgegeben',
    remaining: 'Verbleibend',
    overBudget: 'Budget überschritten',
    safeBudget: 'Im Budgetrahmen',
    setPin: 'PIN festlegen',
    pinActive: 'Konto ist PIN-geschützt',
    exportTitle: 'Finanzberichte exportieren',
    exportDesc: 'Herunterladen als PDF, Excel oder CSV',
    exportPdf: 'PDF-Bericht',
    exportExcel: 'Excel-Tabelle',
    exportCsv: 'CSV-Datei',
    exportJson: 'JSON-Sicherung',
    analytics: 'Statistiken & Analysen',
    analyticsDesc: 'Ausgabenübersicht und Diagramme',
    manageMembers: 'Mitglieder verwalten',
    manageMembersDesc: 'Mitglieder und Budgets verwalten',
    addMember: 'Mitglied hinzufügen',
    memberName: 'Name',
    memberRole: 'Rolle',
    monthlyBudget: 'Monatsbudget',
    quickExpense: 'Schnellausgabe',
    quickIncome: 'Schnelleinnahme',
    allCategories: 'Alle Kategorien',
    filterByCategory: 'Nach Kategorie filtern',
    clearFilters: 'Filter zurücksetzen',
    noResults: 'Keine Ergebnisse',
    addFirstTransaction: 'Erste Transaktion hinzufügen',
    beneficiaryAllFamily: 'Ganze Familie',
    forMyself: 'Für mich',
    generalFamily: 'Allgemein',

    cat_food: 'Lebensmittel & Supermarkt',
    cat_housing: 'Wohnen & Miete',
    cat_utilities: 'Nebenkosten & Rechnungen',
    cat_transport: 'Transport & Treibstoff',
    cat_health: 'Gesundheit & Medizin',
    cat_education: 'Bildung & Schule',
    cat_entertainment: 'Freizeit & Restaurant',
    cat_shopping: 'Einkaufen & Kleidung',
    cat_personal: 'Taschengeld & Persönliches',
    cat_debt: 'Schulden & Raten',
    cat_investments: 'Sparen & Investieren',
    cat_salary: 'Monatsgehalt',
    cat_business: 'Gewerbe & Ertrag',
    cat_gift: 'Geschenke & Boni',
    cat_other: 'Sonstiges',

    role_father: 'Vater (Familienoberhaupt)',
    role_mother: 'Mutter',
    role_son: 'Sohn',
    role_daughter: 'Tochter',
    role_grandfather: 'Großvater',
    role_grandmother: 'Großmutter',
    role_other: 'Anderes Mitglied',

    pm_cash: 'Bargeld',
    pm_card: 'Bankkarte / Kreditkarte',
    pm_bank_transfer: 'Banküberweisung',
    pm_digital_wallet: 'Digitales Wallet',
    pm_other: 'Andere Methode',
  },

  // Fallbacks for other languages automatically fall back to en/ar
  hi: { appName: 'पारिवारिक खर्च' },
  id: { appName: 'Pengeluaran Keluarga' },
  ms: { appName: 'Perbelanjaan Keluarga' },
  bn: { appName: 'পারিবারিক ব্যয়' },
  ru: { appName: 'Семейные Расходы' },
  zh: { appName: '家庭支出管理' },
  ja: { appName: '家族の支出管理' },
  ko: { appName: '가족 지출 관리' },
  pt: { appName: 'Despesas Familiares' },
  it: { appName: 'Spese Familiari' },
  fa: { appName: 'هزینه‌های خانواده' },
};

interface LanguageContextType {
  language: LanguageCode;
  languageInfo: LanguageInfo;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, defaultText?: string) => string;
  formatCategory: (category: string) => string;
  formatRole: (role: string) => string;
  formatPaymentMethod: (method: string) => string;
  formatDate: (dateStr: string) => string;
  formatCurrencyAmount: (amount: number, symbol?: string) => string;
  dir: 'rtl' | 'ltr';
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'family_expenses_lang_v1';

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    try {
      const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY) as LanguageCode;
      if (saved && (translations[saved] || LANGUAGES.some(l => l.code === saved))) {
        return saved;
      }
    } catch {
      // ignore
    }
    return 'ar'; // Default language
  });

  const languageInfo = useMemo(() => {
    return LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];
  }, [language]);

  const dir = languageInfo.dir;
  const isRTL = dir === 'rtl';

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    } catch {
      // ignore
    }
    // Update HTML dir and lang attributes immediately
    const info = LANGUAGES.find((l) => l.code === lang);
    const targetDir = info?.dir || 'ltr';
    document.documentElement.dir = targetDir;
    document.documentElement.lang = lang;
    document.body.dir = targetDir;
  };

  useEffect(() => {
    // Update HTML dir and lang attributes on mount and change
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
    document.body.dir = dir;
  }, [dir, language]);

  const t = (key: string, defaultText?: string): string => {
    const currentDict = translations[language] || translations.en;
    if (currentDict && currentDict[key]) {
      return currentDict[key];
    }
    // Fallback to English, then Arabic
    if (translations.en[key]) return translations.en[key];
    if (translations.ar[key]) return translations.ar[key];
    return defaultText || key;
  };

  const formatCategory = (category?: string): string => {
    if (!category || typeof category !== 'string') return '';
    const key = `cat_${category.toLowerCase()}`;
    const translated = t(key);
    if (translated && translated !== key) return translated;
    return category;
  };

  const formatRole = (role?: string): string => {
    if (!role || typeof role !== 'string') return '';
    const key = `role_${role.toLowerCase()}`;
    const translated = t(key);
    if (translated && translated !== key) return translated;
    return role;
  };

  const formatPaymentMethod = (method?: string): string => {
    if (!method || typeof method !== 'string') return '';
    const key = `pm_${method.toLowerCase()}`;
    const translated = t(key);
    if (translated && translated !== key) return translated;
    return method;
  };

  const formatDate = (dateStr: string): string => {
    try {
      const date = new Date(dateStr);
      const today = new Date();
      const yesterday = new Date();
      yesterday.setDate(today.getDate() - 1);

      const isToday = date.toDateString() === today.toDateString();
      const isYesterday = date.toDateString() === yesterday.toDateString();

      if (isToday) return t('today');
      if (isYesterday) return t('yesterday');

      const locale = isRTL ? 'ar-SA' : language === 'en' ? 'en-US' : language;
      return new Intl.DateTimeFormat(locale, {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        weekday: 'short',
      }).format(date);
    } catch {
      return dateStr;
    }
  };

  const formatCurrencyAmount = (amount: number, symbol: string = 'ر.س'): string => {
    try {
      const locale = isRTL ? 'ar-SA' : 'en-US';
      const formatted = new Intl.NumberFormat(locale, {
        minimumFractionDigits: 0,
        maximumFractionDigits: 2,
      }).format(amount);
      return isRTL ? `${formatted} ${symbol}` : `${symbol} ${formatted}`;
    } catch {
      return `${amount} ${symbol}`;
    }
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        languageInfo,
        setLanguage,
        t,
        formatCategory,
        formatRole,
        formatPaymentMethod,
        formatDate,
        formatCurrencyAmount,
        dir,
        isRTL,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
